vich_uploader:
    db_driver: orm
    mappings:
        traobject_pictures:
            uri_prefix:         '%app.path.uploads_dir%'
            upload_destination: '%kernel.root_dir%/../public/%app.path.uploads_dir%'